#!/usr/bin/env python2.7
import time

print("Starting up...")
time.sleep(10)
print("10 Seconds elapsed...")
time.sleep(10)
print("20 Seconds elapsed...")
time.sleep(10)
print("30 Seconds elapsed...")
time.sleep(10)
print("40 Seconds elapsed...")
time.sleep(10)
print("50 Seconds elapsed...")
time.sleep(10)
print("60 Seconds elapsed...")
print("One Minute elapsed...")

time.sleep(10)
print("70 Seconds elapsed...")
time.sleep(10)
print("80 Seconds elapsed...")
time.sleep(10)
print("90 Seconds elapsed...")
time.sleep(10)
print("100 Seconds elapsed...")
time.sleep(10)
print("110 Seconds elapsed...")
time.sleep(10)
print("120 Seconds elapsed...")
print("Two Minutes elapsed...")

time.sleep(10)
print("130 Seconds elapsed...")
time.sleep(10)
print("140 Seconds elapsed...")
time.sleep(10)
print("150 Seconds elapsed...")
time.sleep(10)
print("160 Seconds elapsed...")
time.sleep(10)
print("170 Seconds elapsed...")
time.sleep(10)
print("180 Seconds elapsed...")
print("Three Minutes elapsed...")

time.sleep(10)
print("190 Seconds elapsed...")
time.sleep(10)
print("200 Seconds elapsed...")
time.sleep(10)
print("210 Seconds elapsed...")
time.sleep(10)
print("220 Seconds elapsed...")
time.sleep(10)
print("230 Seconds elapsed...")
time.sleep(10)
print("240 Seconds elapsed...")
print("Four Minutes elapsed...")

time.sleep(10)
print("250 Seconds elapsed...")
time.sleep(10)
print("260 Seconds elapsed...")
time.sleep(10)
print("270 Seconds elapsed...")
time.sleep(10)
print("280 Seconds elapsed...")
time.sleep(10)
print("290 Seconds elapsed...")
time.sleep(10)
print("300 Seconds elapsed...")
print("Five Minutes elapsed...")
print("Dummy Task Completed...")
